# Generated by Django 4.2.27 on 2025-12-25 06:46

from django.db import migrations, models
import django.db.models.deletion
import mcp_bridge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this GitLab connection', max_length=200, unique=True)),
                ('instance_url', models.URLField(help_text='GitLab instance URL (e.g., https://gitlab.com)')),
                ('client_id', models.CharField(help_text='OAuth Application Client ID', max_length=200)),
                ('client_secret', mcp_bridge.models.EncryptedTextField(help_text='OAuth Application Client Secret')),
                ('access_token', mcp_bridge.models.EncryptedTextField(blank=True, help_text='OAuth Access Token', null=True)),
                ('refresh_token', mcp_bridge.models.EncryptedTextField(blank=True, help_text='OAuth Refresh Token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitLab Connection',
                'verbose_name_plural': 'GitLab Connections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider name', max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (Local)')], max_length=20)),
                ('base_url', models.URLField(help_text='API Base URL (e.g., https://api.openai.com/v1 or http://localhost:11434 for Ollama)')),
                ('api_key', mcp_bridge.models.EncryptedTextField(blank=True, help_text='API Key (not required for Ollama)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Channel name', max_length=200, unique=True)),
                ('channel_type', models.CharField(choices=[('slack', 'Slack Webhook'), ('teams', 'Microsoft Teams Webhook')], max_length=20)),
                ('webhook_url', mcp_bridge.models.EncryptedTextField(help_text='Webhook URL for notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('trigger_type', models.CharField(choices=[('on_error', 'On Error Detection'), ('on_fix_generated', 'On Fix Generation'), ('on_critical', 'On Critical Errors Only')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mcp_bridge.notificationchannel')),
            ],
            options={
                'verbose_name': 'Notification Rule',
                'verbose_name_plural': 'Notification Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(help_text='Local identifier/name for this repository', max_length=200)),
                ('gitlab_project_id', models.IntegerField(help_text='GitLab Project ID')),
                ('gitlab_project_path', models.CharField(help_text='GitLab project path (e.g., group/project)', max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gitlab_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='mcp_bridge.gitlabconnection')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'ordering': ['local_name'],
                'unique_together': {('gitlab_connection', 'local_name')},
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='Model identifier (e.g., gpt-4o, claude-3-5-sonnet, qwen2.5-coder:7b)', max_length=200)),
                ('display_name', models.CharField(help_text='Human-readable model name', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default model for analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='mcp_bridge.llmprovider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'model_id'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
