# Generated by Django 4.2.27 on 2025-12-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='force_ollama',
            field=models.BooleanField(default=False, help_text='Force use of Ollama (local) models for this repository to ensure privacy'),
        ),
    ]
