# Generated by Django 4.2.27 on 2025-12-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp_bridge", "0002_repository_force_ollama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("ollama", "Ollama (Local)"),
                    ("gemini", "Google Gemini"),
                ],
                max_length=20,
            ),
        ),
    ]
