# Generated by Django 4.2.27 on 2025-12-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp_bridge", "0003_alter_llmprovider_provider_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="base_url",
            field=models.URLField(
                help_text="API Base URL (e.g., https://api.openai.com/v1, https://generativelanguage.googleapis.com for Gemini, or http://localhost:11434 for Ollama). Can be left default for Gemini."
            ),
        ),
    ]
